#include "system_reset.h"
#include "FreeRTOS.h"
#include "task.h"
#include "stm32f4xx_hal.h"
#include "lwip/netif.h"
#include "ethernetif.h"
#include "stm32f4xx.h"

#include <stdio.h>

/* Extern handles generated by CubeMX */
extern ETH_HandleTypeDef heth;
extern SPI_HandleTypeDef hspi3;
extern UART_HandleTypeDef huart3;
extern struct netif gnetif;

void system_reset_hard(void)
{
    NVIC_SystemReset();
    while (1) { } // Should never be reached
}

/* Main graceful reset function */
void system_reset_graceful(void)
{
    taskENTER_CRITICAL();
    __disable_irq();

    /* Bring network interface down */
    netif_set_down(&gnetif);

    /* Deinitialize Ethernet (also stops DMA) */
    //ethernetif_deinit(&gnetif);

    /* Deinit peripherals */
    HAL_SPI_DeInit(&hspi3);

    HAL_UART_DeInit(&huart3);

    /* Reset all clocks and peripherals to default state */
    HAL_DeInit();

    /* Trigger MCU reset */
    NVIC_SystemReset();

    while (1) { } // Should never be reached
}
